Docs/brain.md, Docs/neuron_list.md, brain.yml, brains/neurotransmitter.yml, core/ConfigurationManager/BrainLoader.py, core/ConfigurationManager/ConfigurationChecker.py, core/ConfigurationManager/SettingLoader.py, core/ConfigurationManager/YAMLLoader.py, core/MainController.py, core/NeuronModule.py, core/OrderAnalyser.py, neurons/__init__.py, neurons/neurotransmitter/README.md, neurons/neurotransmitter/__init__.py, neurons/neurotransmitter/neurotransmitter.py, test.py
- add neurotransmitter neuron
- review yaml include statement
=> Neurotransmitter

core/CrontabManager.py, core/MainController.py, core/RestAPI/FlaskAPI.py, core/ShellGui.py, core/SynapseLauncher.py, install/files/python_requirements.txt, kalliope.py
remove direct acces to get_bain. only the entrypoint call it and then pass the brain to sub classes
=> Refacto brain loading

brain.yml, brains/say.yml, core/ConfigurationManager/ConfigurationChecker.py, core/ConfigurationManager/YAMLLoader.py, core/ShellGui.py, kalliope.py, settings.yml
- crontab manager was broken due to include statement with relative path
switch to acapela as default TTS
=> fix event with crontab

install/files/python_requirements.txt, install/install.retry
=> Dev into master

Docs/settings.md, core/MainController.py, install/install_kalliope.sh, trigger/snowboy/snowboy.py, trigger/snowboy/snowboydecoder.py
Snowboy is now a real thread. Child daemon of kalliope main program.
We also pause snowboy instead of killing it when waiting for STT return and so we won a couple of ms in the process.
=> fix ctrl-c. 

Docs/neuron_list.md, core/NeuronModule.py, core/Tests/test_brain_loader.py, install/files/python_requirements.txt, manual_testing.py, neurons/uri/README.md, neurons/uri/tests/data_post_test.json, neurons/uri/tests/test_get_template.j2, neurons/uri/tests/test_uri_neuron.py, neurons/uri/tests/uri_test_brain.yml, neurons/uri/uri.py
- neuron URI
- tests for the neuron (usage of a REST API mock lib)
- doc 
- update neuron list (remove unused column "used to sort")
- a neuron can get his name from the mother class (used for logging in this case)
=> add neuron URI to play with web services

CHANGELOG.md, brains/wikipedia.yml, core/Tests/test_brain_loader.py, neurons/wikipedia/__init__.py, neurons/wikipedia_searcher/README.md, neurons/wikipedia_searcher/__init__.py, neurons/wikipedia_searcher/tests/test_wikipedia_searcher.py, neurons/wikipedia_searcher/wikipedia_searcher.py
neuron renamed to prevent conflict with the wikipedia python lib
unit tests added
=> Fix wikipedia neuron

Docs/installation/ubuntu_16.04.md
Fix path to settings in ubuntu install docs
=> Fix path in ubuntu install docs

Docs/rest_api.md, Tests/test_rest_api.py, neurons/script/README.md, neurons/script/script.py, neurons/script/tests/test_script.py, neurons/script/tests/test_script.sh, neurons/script/tests/test_script_cat.sh, neurons/shell/shell.py, neurons/shell/tests/test_shell.py
unit test for 
- REST API
- shell neuron 
- script neuron
neuron shell improvement: can now run a script asynchronously like the shell neuron
=> add some unit tests 

Docs/settings.md, kalliope/brain.yml, kalliope/brains/default.yml, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/Models/Settings.py, kalliope/core/OrderAnalyser.py, kalliope/settings.yml
[89] Implements default synapse when order is not found
=> [89] Implements default synapse when order is not found

Docs/brain.md, Docs/settings.md, Tests/__init__.py, kalliope/brain.yml, kalliope/brains/default.yml, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/Models/Settings.py, kalliope/core/OrderAnalyser.py, kalliope/core/Utils/__init__.py, kalliope/settings.yml
=> Bacardi55 dev

Tests/test_brain_loader.py, Tests/test_rest_api.py, Tests/test_settings_loader.py, Tests/test_singleton.py, kalliope/__init__.py, kalliope/_version.py, kalliope/core/ConfigurationManager/BrainLoader.py, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/MainController.py, kalliope/core/Models/Singleton.py, kalliope/core/NeuronModule.py, kalliope/core/OrderListener.py, kalliope/core/RestAPI/utils.py, kalliope/core/ShellGui.py, kalliope/core/TTS/TTSModule.py, kalliope/core/__init__.py, kalliope/neurons/ansible_playbook/tests/test_ansible_playbook.py, kalliope/neurons/script/tests/test_script.py, kalliope/neurons/uri/tests/test_uri_neuron.py, kalliope/trigger/snowboy/snowboydetect.py
- refactor singleton
- active back unit tests
=> review singleton + active back tests

Docs/brain.md, Docs/installation/debian_jessie.md, Docs/neuron_list.md, Docs/neurons.md, Docs/stt.md, Docs/tts.md
Fix internal markdown links
Fix some typos
=> fix markdown link and some typos

kalliope/core/Utils/Utils.py
Hi.
I ran into a problem when trying to run the application as a systemd service. Python is not setting encoding of stdout correctly, so first print of non english characters breaks everything.  
[Here is good explanation](http://www.macfreek.nl/memory/Encoding_of_Python_stdout)
Anyway, here is my option solution.
P.S. thanks for this great project ;)
=> fix encoding of python stdout

Docs/installation.md, Docs/installation/ubuntu_14.04.md, Docs/installation/ubuntu_16.04.md
Update some Dependancy requirements for Ubuntu 14.04 +
validation Install for fresh Distrib
=> [Install] Validation Ubuntu14.04

Tests/test_neuron_module.py, Tests/test_order_analyser.py, brain_examples/neurotransmitter.yml, kalliope/core/Models/Brain.py, kalliope/core/NeuronModule.py, kalliope/core/OrderAnalyser.py, kalliope/core/OrderListener.py, kalliope/core/SynapseLauncher.py, kalliope/neurons/neurotransmitter/README.md, kalliope/neurons/neurotransmitter/neurotransmitter.py, kalliope/stt/google/google.py
[Feature] Improvement of the neurontransmitter to manage params
[Feature] #135 fix typos and algos
=> [Feature]#135 Improve neuron neuronTransmitter to manage params in answers

kalliope/core/NeuronModule.py
manage dynamic class instantiation for community tts by giving the tts folder
=> [Fix] #166 tts community

kalliope/core/OrderListener.py
manage dynamic instatiation of aprovided  community stt by giving the resources directory
=> [fix] community stt

Docs/neuron_list.md
=> Add community neurons

Docs/installation/raspbian_jessie.md, kalliope/core/MainController.py, kalliope/settings.yml
review installation process +
Add raspbian supported version +
tests on rpi3
=> Supported raspbian

Docs/neuron_list.md
+ fix indent of the markdown table
=> add HUE neuron into the community list

Docs/installation.md, Docs/installation/quickstart.md
updated docs with the references to the german starter kit.
=> updated docs with references to german starterkit

Tests/test_brain_loader.py, Tests/test_neuron_module.py, kalliope/core/ConfigurationManager/BrainLoader.py, kalliope/core/NeuronModule.py
- fix neurotransmitter in order to Closes #219. The main thread is now waiting for the end of the neurotransmitter process before continuing
- fix global variable loading in BrainLoader. Use a recursive method to handle dict, list and string from different level in parameters of a neuron
=> fix neurotransmitter

Docs/stt_list.md, kalliope/stt/wit/README.md
=> renamed wit.ai to wit in docs

kalliope/stt/cmusphinx/README.md, kalliope/stt/cmusphinx/cmusphinx.py
Hello
pull for add langage selection to CMUSphinx:
[Doc of speech_recognition for installing other languages](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst#installing-other-languages)
=> Add language option to CMUSphinx

Docs/neurons.md, Tests/test_neuron_launcher.py, brain_examples/neurotransmitter.yml, brain_examples/openweathermap.yml, brain_examples/twitter.yml, brain_examples/wikipedia.yml, kalliope/core/NeuronLauncher.py
Now input argument from order are passed to neurons like a jinja variable.
This in order to close #254
=> Review args

Docs/neurons.md, Tests/test_neuron_module.py, kalliope/core/NeuronModule.py
Update function to can do that
```
---
- name: "say-hello-fr"
signals:
- order: "Dit bonjour en espagnol"
neurons:
- say:
message:
- "Buenos dias"
tts: 
pico2wave:
language: "es-ES"
```
=> update function _update_cache_var to _update_params

kalliope/core/TTS/TTSModule.py, kalliope/core/Utils/FileManager.py, kalliope/tts/acapela/README.md, kalliope/tts/acapela/acapela.py, kalliope/tts/pico2wave/README.md
=> fix acapela TTS

Tests/test_neuron_launcher.py, Tests/test_utils.py, kalliope/core/Models/APIResponse.py, kalliope/core/NeuronLauncher.py, kalliope/core/NeuronModule.py, kalliope/core/Utils/Utils.py
=> [Fix] #263 encoding on neuron launcher and serialize + add test

kalliope/core/Players/PyAlsaAudioPlayer.py
improved alsaplayer; set default to sysdefault for RPi3 to work; see #234
=> [dev/pyaudio] improved alsaplayer

Docs/installation/raspbian_jessie.md
Cleans up some english and spelling errors. Removes pronouns. Removed the word "can" in a lot of places. This is a tutorial that instructs. "Can" is more of a request instead of a specific instruction.
Just trying to help. No problem if you do not want to use this change
=> Updated raspbian_jessie.md

Docs/settings.md, Tests/test_neuron_launcher.py, Tests/test_synapse_launcher.py, brain_examples/neurotimer.yml, kalliope/core/NeuronLauncher.py
Add the possibility of using dict in global var file
@LaMonF plz review the "neurotimer" PR first. I wrote this one over it.
=> Dict in global var

Docs/trigger.md
I have also translated the starter. You will find it here: https://github.com/frnmst/kalliope_starter_it
=> Added italian language trigger to the docs.

Docs/tts_list.md, kalliope/tts/espeak/README.md, kalliope/tts/espeak/__init__.py, kalliope/tts/espeak/espeak.py
To meet this demand: [https://github.com/Ultchad/kalliope-espeak/issues/3](https://github.com/Ultchad/kalliope-espeak/issues/3)
I hope I have not forgotten this time 😄
=> add espeak tts to Kalliope core

Docs/rest_api.md, Tests/test_cortex.py, brain_examples/mute.yml, kalliope/__init__.py, kalliope/core/Cortex.py, kalliope/core/RestAPI/FlaskAPI.py, kalliope/core/SignalLauncher.py, kalliope/neurons/mute/README.md, kalliope/neurons/mute/mute.py, kalliope/signals/order/order.py
=> add mute neuron mute mute control rom api

Tests/test_neuron_parameter_loader.py, kalliope/core/NeuronParameterLoader.py
Fix and add debug 
Add tests cases
=> #341 manage case between order variables

Tests/test_lifo_buffer.py, kalliope/core/LIFOBuffer.py, kalliope/core/NeuronModule.py, kalliope/neurons/neurotimer/neurotimer.py, kalliope/neurons/neurotransmitter/neurotransmitter.py, kalliope/neurons/neurotransmitter/tests/test_neurotransmitter.py
=> Fix usage of neurotransmitter + neurotimer

CHANGELOG.md, Docs/settings.md, Tests/test_models.py, Tests/test_settings_loader.py, brain_examples/neurotimer.yml, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/Models/RecognitionOptions.py, kalliope/core/Models/Settings.py, kalliope/core/Models/SttOptions.py, kalliope/core/NeuronExceptions.py, kalliope/core/NeuronLauncher.py, kalliope/core/NeuronModule.py, kalliope/core/ShellGui.py, kalliope/neurons/neurotimer/README.md, kalliope/neurons/neurotimer/neurotimer.py, kalliope/settings.yml, kalliope/signals/order/order.py, kalliope/stt/Utils.py
- add back forwarded parameters to neurotimer
- failed neuron are now skiped. no more blocking
- order listener now started after playing the random answer
Once your review is done, you can PR Dev to master to release the v0.4.6 version.
=> Fix release v0.4.6

Docs/rest_api.md
First attempt to add clear documentation about the status of the API response in case of neurotransmitter (status "waiting_for_answer")
=> fix #375 by adding documentation about neurotransmitter API response

Tests/test_neuron_parameter_loader.py, kalliope/core/NeuronParameterLoader.py
=> [Fix] #390 retrieve params when user order contains non matching words

Tests/test_neuron_module.py, install/files/python_requirements.txt, kalliope/core/RestAPI/FlaskAPI.py, kalliope/neurons/script/tests/test_script.py, kalliope/neurons/shell/tests/test_shell.py, kalliope/neurons/systemdate/tests/test_systemdate.py, kalliope/neurons/uri/tests/test_uri_neuron.py, kalliope/settings.yml, kalliope/tts/pico2wave/pico2wave.py, kalliope/tts/voicerss/README.md, kalliope/tts/voicerss/voicerss.py, setup.py
merge #396 first then rebase this on dev
#395
Update the voicerss tts using the last official python lib wrapper
Add new options
=> voicerss wrapper

Tests/test_order_analyser.py, kalliope/core/NeuronModule.py, kalliope/core/OrderAnalyser.py, kalliope/signals/order/README.md
=> add feature normal, strict and ordered-strict order

Tests/test_utils.py, kalliope/core/Utils/Utils.py
=> fix regex when removing spaces in brackets when the sentence is json

Tests/test_file_manager.py, kalliope/core/Utils/FileManager.py
=> Fix conditional on python version

Docs/neurons.md, kalliope/_version.py, kalliope/core/NeuronModule.py, kalliope/signals/order/order.py
Closes #418 
This allow to send message to magic mirror project for example.
=> save in memory the last tts message and order

kalliope/core/Models/Neuron.py, kalliope/neurons/kill_switch/kill_switch.py
=> [Fix] #420 kill_switch os_exit to kill all process

Tests/test_notification_manager.py, Tests/test_rest_api.py, kalliope/core/ConfigurationManager/ConfigurationChecker.py, kalliope/core/NotificationManager.py, kalliope/core/SignalModule.py, kalliope/neurons/signals/README.md, kalliope/neurons/signals/signals.py, kalliope/signals/event/event.py, kalliope/signals/geolocation/README.md, kalliope/signals/geolocation/geolocation.py, kalliope/signals/mqtt_subscriber/mqtt_subscriber.py, kalliope/signals/order/README.md, kalliope/signals/order/order.py, setup.py
Add an Interactive mode in order to close #384 
@bacardi55 this one is for you, if you can give us a feedback if you have time.
=> add signals neuron

Docs/settings.md, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/HookManager.py, kalliope/core/Models/settings/Options.py, kalliope/settings.yml, kalliope/signals/order/order.py, kalliope/stt/Utils.py, kalliope/stt/apiai/apiai.py, kalliope/stt/bing/bing.py, kalliope/stt/cmusphinx/cmusphinx.py, kalliope/stt/google/google.py, kalliope/stt/houndify/houndify.py, kalliope/stt/wit/wit.py
- add STT timeout feature #435 
- fix option loading when a key is missing from the setting
- fix hook settings, hooks don't need to be declared empty anymore when not used
- add hook on_stt_error which is raised when mic failure or stt service failure #214
=> STT timeout + new hook

Docs/tts_list.md, kalliope/tts/marytts/README.md, kalliope/tts/marytts/__init__.py, kalliope/tts/marytts/marytts.py
=> Add MaryTTS

Tests/test_dna_loader.py, Tests/test_synapse_launcher.py, kalliope/core/ConfigurationManager/ConfigurationChecker.py, kalliope/core/ConfigurationManager/DnaLoader.py, kalliope/core/SynapseLauncher.py
also add the cortex to the signal output
=> Fix signal install + cortex usable with signal

kalliope/neurons/neurotimer/README.md
Fixed a couple of errors in the example that prevented it from working.
=> Fixed example.

.travis.yml, install/files/python_requirements.txt, kalliope/core/ResourcesManager.py, kalliope/neurons/ansible_playbook/ansible_playbook.py, kalliope/neurons/ansible_playbook/tests/test_ansible_playbook.py, kalliope/neurons/ansible_playbook/tests/test_ansible_playbook_neuron.retry, setup.py
=> update ansible to the last available version

install/files/python_requirements.txt, kalliope/tts/googletts/googletts.py, setup.py
The library got some nice features, including unlimited lengths of text to be read.
=> Update googletts to use gTTS library

Tests/test_trigger_launcher.py, kalliope/core/TriggerLauncher.py
In order to use a community trigger.
=> Add trigger_folder

docs/brain/neurons/kalliope_version.md, kalliope/neurons/kalliope_version/kalliope_version.py
=> add kalliope version neuron

CHANGELOG.md, kalliope/core/ConfigurationManager/YAMLLoader.py, kalliope/core/OrderAnalyser.py, kalliope/neurons/ansible_playbook/ansible_playbook.py, setup.py
=> #550 fix deprecated yaml loader

Tests/test_settings_loader.py, kalliope/core/ConfigurationManager/SettingLoader.py, kalliope/core/HookManager.py
=> [Fix] #556 introduce a specific variable to track the google tracking id

docs/installation/upgrade.md, kalliope/core/Lifo/LifoManager.py, mkdocs.yml
=> Upgrade doc

docker/official_image/alsa-pulse.conf, docker/official_image/asound-pulse.conf, docker/official_image/pulse-client.conf, docker/official_image/ubuntu_18_04.dockerfile, docs/installation/docker.md
In order to close #545
The image is available on [Docker hub here](https://hub.docker.com/r/kalliope/kalliope_ubuntu)
=> [Feature] add kalliope official Docker image

install/rpi_install_kalliope.sh
Little bug, found by one of our beta testers :)
=> Fix path for copy pulseaudio.service

kalliope/core/NeuronLauncher.py
In order to close [#613](https://github.com/kalliope-project/kalliope/issues/613)
=> Prevent crashing kalliope if neuron fails
