kalliope-project/kalliope

- Docs/dev_env_install.md
install/files/python_requirements.txt does not exist while the sources are not downloaded. The installation of python libs thus happens after cloning the repo.
> Correct the order of operations

- core/ConfigurationManager/SettingLoader.py
The mistake probably comes from a hasty copy/paste (which may be a sign that this code should be refactored BTW)!
> Fix a variable naming mistake: "trigger" instead of "tts"

- setup.py
Hi,
This is a small PR for the review_install branch. I just fix the entry point config in the setup.py file because we must link to main function in `kalliope.py` now and not in `__init__.py` anymore.
Cheers
> Fix the entry point in setup.py (target review_install branch)

- Docs/neuron_list.md
- install/files/python_requirements.txt
- kalliope/brain.yml
- kalliope/brains/rss_reader.yml
- kalliope/neurons/rss_reader/README.md
- kalliope/neurons/rss_reader/__init__.py
- kalliope/neurons/rss_reader/rss_reader.py
- kalliope/neurons/rss_reader/tests/test_rss_reader.py
- kalliope/templates/en_rss.j2
- kalliope/templates/fr_rss.j2
- setup.py
Add a rss reader neuron
Allow to get items from RSS feed.
There is an option to limit the number of items to return
NB: 
I rebase to last dev branch and I had to change import in Utils `__init__.py` to make it works 
`from kalliope.core.Utils.Utils import Utils`
instead of 
`from kalliope.core.Utils import Utils`
My knowlegde about python are very low
> Rss reader neuron

- Docs/installation/debian_jessie.md
- Docs/installation/raspbian_jessie.md
- Docs/installation/ubuntu_16.04.md
I rewrote the 3 install procedures to use pip and setup.py like already discuss in #100 .
I test the new install procedures on Debian Jessie and Ubuntu 16.04 but not on Raspian Jessie because I don't have a Raspberry Pi available for testing now.
Cheers
> Rewrite the install documentations to use setup.py and pip. #100 (target branch dev)

- kalliope/neurons/shell/README.md
- kalliope/neurons/shell/shell.py
Add ability to add argument to shell command in shell neuron
> Add ability to add argument to shell command in shell neuron

- Docs/settings.md
- Tests/settings/settings_test.yml
- Tests/test_rest_api.py
- Tests/test_settings_loader.py
- install/files/python_requirements.txt
- kalliope/core/ConfigurationManager/SettingLoader.py
- kalliope/core/MainController.py
- kalliope/core/Models/RestAPI.py
- kalliope/core/RestAPI/FlaskAPI.py
- kalliope/settings.yml
- setup.py
As a follow up to #155, the goal here is to enable CORS request so external app can use the API.
In this pull request, the option let you activate CORS requests from any origins (so it's either close or open for all).
The second part of this feature will consist of leveraging [flask_cors options](https://flask-cors.readthedocs.io/en/latest/api.html#extension) to let user configure a limited set of origins.
> Add an option to allow CORS requests

- CHANGELOG.md
- kalliope/_version.py
- kalliope/core/ResourcesManager.py
in order to fix this when installing a neuron
```
Cloning repository...
Checking repository...
2017-01-18 08:20:56,420 :: DEBUG :: File path to load: /tmp/kalliope/resources/kalliope_new_module_temp_name/dna.yml 
2017-01-18 08:20:56,423 :: DEBUG :: [ResourcesManager] DNA file content: Dna: name: wikipedia_searcher, type: neuron, author: The dream team of Kalliope project, kalliope_supported_version: [0.4], tags: ['wikipedia', 'search engine', 'wiki']
2017-01-18 08:20:56,423 :: DEBUG :: [ResourcesManager] Current installed version of Kalliope: 0.4.1
2017-01-18 08:20:56,423 :: DEBUG :: [ResourcesManager] Module supported version: [0.4]
Traceback (most recent call last):
File "/usr/local/bin/kalliope", line 11, in <module>
load_entry_point('kalliope==0.4.1', 'console_scripts', 'kalliope')() …
```
> fix community installation neuron

- Docs/installation.md
- Docs/installation/quickstart.md
- Docs/installation/raspbian_jessie.md
- Docs/settings.md
- README.md
I would like to push this into master directly. Changes are only concerning the doc.
I've added a quick start doc and a link to the [pre compiled Raspbian image](https://github.com/kalliope-project/kalliope/releases/tag/v0.4.2).
> update doc, add quickstart and pre compiled raspbian image

- kalliope/core/ResourcesManager.py
- changed hardcoded tmpfile location to location provided by tempfile.
- changed os.rename to shutil.move
If working in a venv environment os.rename fails, because source and dest are not on the same filesystem. Same should happen in cases where /tmp is not on the same filesystem
shutil.move can handle it and should not have drawbacks.
> Fix Resourcesmanager

- Docs/kalliope_cli.md
- kalliope/__init__.py
added an option "--run-order" to directly run an order from command line.
Usage:
```bash
kalliope start --run-order "hello"
```
By the way a changed the order of processing the args in _init__.py
This way an "kalliope install" is possible without loading the brain file first. There is no need to have a brain file available for an install command.
This fixes the problem that if you delete and reinstall a neuron you must remove it from the brain.yml first.
> added option --run-order

- Docs/settings.md
- kalliope/brain.yml
- kalliope/core/MainController.py
- kalliope/settings.yml
- Run the default synapse if this one exist and if the STT engine doesn't return an order in order to Closes #196
- disable the rest api by default in settings for better performance on Rpi.
> run default synapse when no order returned by STT

- kalliope/neurons/ansible_playbook/README.md
- kalliope/neurons/kill_switch/README.md
- kalliope/neurons/neurotransmitter/README.md
- kalliope/neurons/say/README.md
- kalliope/neurons/script/README.md
- kalliope/neurons/shell/README.md
- kalliope/neurons/sleep/README.md
- kalliope/neurons/systemdate/README.md
- kalliope/neurons/uri/README.md
We do not release a new version with this PR. It's only to fix the doc of our core neurons in the master branch which is inconsistent with the code of the 0.4.4.
> doc update, replace old syntax "args" by jinja input value

- kalliope/stt/cmusphinx/cmusphinx.py
Making use of `keyword_entries` allows to path a phrase dictionary to sphinx (full description [here](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst#recognizer_instancerecognize_sphinxaudio_data-language--en-us-keyword_entries--none-show_all--false)). This makes sphinx much more reliable in the context of 
kalliope since the user can narrow down the grammar to the actual relevant phrases.
Keyword entries consist of a phrase and a sensitivity level ranging from 0 (insensitive; more false negatives) to 1 (very sensitive; more false positives).
```yaml
speech_to_text:
- cmusphinx:
language: "en-US"
keyword_entries:
- ["goodbye", 1]
- ["hello world", 0.8]
```
> add ‘keyword_entries’ to sphinx speech recognition

- kalliope/stt/cmusphinx/README.md
Added the feature documentation and also fixed the settings example for basic usage (wrong indent; lacking colon)
> Add documentation for `keyword_entries` to cmusphinx/Readme

- kalliope/core/ConfigurationManager/SettingLoader.py
Configuration now checks for recognition_options in settings.yml instead of RecognitionOptions
> Fix #373: Configuration now checks for recognition_options 

- Docs/kalliope_cli.md
- Docs/settings.md
- Tests/settings/settings_test.yml
- Tests/test_models.py
- Tests/test_settings_loader.py
- kalliope/__init__.py
- kalliope/core/ConfigurationManager/SettingLoader.py
- kalliope/core/Models/Settings.py
- kalliope/settings.yml
- kalliope/signals/order/order.py
[Implements #376]
This PR adds the ability to start Kalliopé muted, either
- by adding ```--muted``` when starting kalliope (eg: ```kalliope start --muted```)
- or by configuring it in the settings.yml like this:
```yaml
start_options:
muted: True # default value is False
```
I decided to create a "start_options" dict instead of just a simple "start_muted: True/False" as I thought it might be useful later on but I can change this if needed.
> Implements #376 : Start Kalliopé muted

- Docs/settings.md
- Tests/settings/settings_test.yml
- Tests/test_hook_manager.py
- Tests/test_settings_loader.py
- kalliope/core/HookManager.py
- kalliope/core/SynapseLauncher.py
- kalliope/settings.yml
This PR adds another Hook method to Kalliope: the `on_order_completed` hook. This hook is set to run after a synapse completes execution.
For my use-case, I've added it to perform cleanups to a ReSpeaker LED array (i.e. turn it off) after the synapse tasks are complete; I make use of `on_order_found` to turn on said LED array, so I needed a way to cleanly turn it off without cluttering up every one of my synapses (and adding unnecessary `sleep` calls everywhere).
The change is not very large: adding the class method for the hook, and then tying it in to the SynapseLauncher by splitting the return. I've added the new hook to the default `settings.yml` in this repo but it would also have to be updated everywhere for this to work (or I could add some 'ignore if not found' logic perhaps? …
> Add new on_order_completed hook

- Tests/test_hook_manager.py
- Tests/test_init.py
- Tests/test_synapse_launcher.py
- kalliope/__init__.py
- kalliope/core/HookManager.py
- kalliope/core/ShellGui.py
- kalliope/core/SynapseLauncher.py
- kalliope/signals/event/event.py
- kalliope/signals/mqtt_subscriber/MqttClient.py
Quick refactoring to remove some duplicate code from the synapse launcher.
Reuse the synapse_by_list_name method to run single synapse.
> [Refacto] Remove duplicate code for synapse launcher

- kalliope/core/Lifo/LIFOBuffer.py
- kalliope/core/PlayerModule.py
- kalliope/core/RestAPI/FlaskAPI.py
Fix LIFO buffer to return Null instead of best crashing.
Not best solution as it should return a serialised answer, but this fix require big refactoring probalbly ...
Basically this is a quick fix to improve user experience with the app.
> [Fix] Return default serialization when kalliope running

- Docs/rest_api.md
- Tests/settings/settings_test.yml
- Tests/test_models.py
- Tests/test_setting_editor.py
- Tests/test_settings_loader.py
- kalliope/core/ConfigurationManager/SettingEditor.py
- kalliope/core/Models/settings/Settings.py
- kalliope/core/Models/settings/Trigger.py
- kalliope/core/RestAPI/FlaskAPI.py
- kalliope/core/Utils/Utils.py
- kalliope/neurons/settings/README.md
- kalliope/neurons/settings/settings.py
Define new endpoints for the rest api to manage Kalliope settings dynamically.
New endpoints : 
| Method | URL                               | Action                             |
|--------|-----------------------------------|------------------------------------|
| GET    | /settings/deaf                    | Get the current deaf status        |
| POST   | /settings/deaf                    | Switch the deaf status             |
| GET    | /settings/mute                    | Get the current mute status        |
| POST   | /settings/mute                    | Switch the mute status             |
| GET    | /settings/energy_threshold        | Get the current energy_threshold   |
| POST   | /settings/energy_threshold        | Update the energy_threshold value  |
| GET    | …
> Rest Api Settings endpoints 

- Tests/test_order_analyser.py
- kalliope/core/OrderAnalyser.py
even if the spoken order match it multiple time. #500
> making sure the called synapse is execute only once

- Tests/test_order_analyser.py
- kalliope/core/OrderAnalyser.py
Now corrections are only applied to the currently tested synapse. #488
> fix stt correction. 

- kalliope/core/Cortex.py
would be nice to have the last stt in memory
A quick way to test the feature could be this:
```
- name: "test-stt-1"
signals:
- order: "Testing"
neurons:
- say:
message:
- "Key values in memory are {{ kalliope_memory }}"
- neurotransmitter:
from_answer_link:
- synapse: "test-stt-2"
answers:
- 'foo'
- 'bar'
default: "test-stt-2"
- name: "test-stt-2"
signals:
- order: "test-stt-2"
neurons:
- say:
message:
- "Last SST is {{ kalliope_memory['kalliope_last_stt_message'] }}"
```
> Fix cortex when saving string

- Tests/files/test-stt-correction.yml
- Tests/test_order_analyser.py
- Tests/test_trigger_launcher.py
- docs/brain/signals/order.md
- kalliope/core/NeuronModule.py
- kalliope/core/OrderAnalyser.py
- kalliope/core/TriggerLauncher.py
- Add matching-type "not-contain"
- Small fix for the STT-Correction:
- if the order is not in lower case and the correction is or the opposite, it will not be found
- if one stt-correction contains more than one word, it will not be found
- Add docs for the new matching-type
> Add new matching-type and small fix for the stt correction

- CHANGELOG.md
- Tests/test_synapse_launcher.py
- kalliope/core/SynapseLauncher.py
Fix - #548
On the synpaseLauncher if the synapse is enabled it is put it in the LIFO queue.  Otherwise it logs the name of the disabled synapse and does not put it in the queue.
> #548 fix disabled synapse with event

- docs/installation/check_env.md
The first step of automatic start is more obvious by finishing the previous sentence with ':' and adding a carriage return.
> Improve readability

- docs/installation/debian.md
The `libsmpeg0` library is necessary only one time to install it.
The raspian and ubuntu version are correct.
> libsmpeg0 is written two times

- docker/official_image/ubuntu_18_04.dockerfile
- docker/testing_debian10.dockerfile
- docker/testing_ubuntu_18_04.dockerfile
- docs/installation/debian.md
- docs/installation/raspbian.md
- docs/installation/ubuntu.md
- docs/settings/tts/pico2wave.md
- install/files/deb-packages_requirements.txt
- install/files/python_requirements.txt
- install/rpi_install_kalliope.sh
- install/rpi_kalliope_install.yml
- kalliope/tts/pico2wave/pico2wave.py
- setup.py
In order to close [#620](https://github.com/kalliope-project/kalliope/issues/620) and [#619](https://github.com/kalliope-project/kalliope/pull/619).
Sox was used to convert the samplerate of pico2wav, because not all usb mics support 16 Khz. With pulseaudio this is not a problem anymore.
> Remove sox dependency

- docs/settings/triggers/snowboy.md
- kalliope/signals/order/order.py
- kalliope/stt/SpeechRecognizer.py
The on_triggered hook get called while the trigger is still active, this can result in a false positiv trigger activation right after a order got executed because the chunks of the trigger are in a queue and get process after unpausing the trigger. 
This hotfix makes sure the trigger get paused before the on_trigger hook get called. 
Also we don't need to write the microphone level to a file, this has got no use for us.
> Hotfix 0.7.0

- Tests/test_utils.py
- kalliope/core/Utils/Utils.py
This implements a caching mechanism to Utils.get_dynamic_class_instantiation() by storing a reference to the to-be-instantiad class in a directory in Utils.klass_cache with the package_path as the key. This should be a side-effect free change that optimizes runtime for class instantiations where those classes maintain state in class attributes.
My specific use case is the vosk STT plugin, which (now) stores its (~50MB) model in a class attribute in order to reduce class instantiation time for each STT pass (juergenpabel/kalliope-vosk@6d63709). Only the first instantation takes about 1-2 secs on a pi4, subsequent instantiations are now instantanious.
> Added cache to Utils.get_dynamic_class_instantiation() 
